import { describe, expect, it } from 'vitest';
import {
  annualise,
  autoAppraise,
  buildSpendProfile,
  cilCharge,
  computeAppraisal,
  irr,
  jvWaterfall,
  sdltCommercial,
  sensitivityGrid,
  weightedComparables,
  type AppraisalInput,
} from '../src/index.js';

/**
 * Golden fixture — the Bournemouth trade-counter reference case (CALCULATIONS.md §12).
 * Expected values were generated by running the prototype's compute() verbatim
 * (Development Appraisal.dc.html) on these inputs. Assert to the penny / basis point.
 */
const CIL_REF = cilCharge(18800 / 0.9, 40); // 40 £/sqm on GIA

const referenceCase: AppraisalInput = {
  units: [
    { label: 'Trade counter units', count: 6, area: 2600, cap: 225 },
    { label: 'Mezzanine offices', count: 1, area: 3200, cap: 240 },
  ],
  efficiency: 90,
  trades: [{ label: 'Build', rate: 105 }],
  profFeePct: 11,
  contingencyPct: 5,
  otherCosts: [
    { label: 'Planning & S106', amount: 150000 },
    { label: 'CIL', amount: CIL_REF },
  ],
  finance: { ltcPct: 60, ratePct: 7.5, periodMonths: 18, salesMonths: 3, arrangementFeePct: 1.5, spendProfile: 'scurve' },
  site: { mode: 'residual', landFixed: 350000, acqPct: 6.8 },
  disposal: { agentPct: 1.5, legalPct: 0.5 },
  targetProfitOnGdvPct: 20,
  jv: { gpCoinvestPct: 10, prefPct: 8, promotePct: 20 },
};

describe('computeAppraisal — Bournemouth golden fixture', () => {
  const R = computeAppraisal(referenceCase, { withCash: true });

  it('areas and revenue', () => {
    expect(R.nia).toBe(18800);
    expect(R.gia).toBeCloseTo(20888.888888888887, 6);
    expect(R.gdv).toBe(4278000);
    expect(R.buildRate).toBe(105);
  });

  it('costs to the penny', () => {
    expect(R.build).toBeCloseTo(2193333.333333333, 2);
    expect(R.fees).toBeCloseTo(241266.66666666663, 2);
    expect(R.cont).toBeCloseTo(109666.66666666664, 2);
    expect(R.otherTotal).toBeCloseTo(227625.00516123703, 2);
    expect(R.saleCosts).toBe(85560);
  });

  it('finance — compounding drawdown model', () => {
    expect(R.interest).toBeCloseTo(104268.46422271417, 2);
    expect(R.arrangement).toBeCloseTo(26312.136238982723, 2);
    expect(R.finance).toBeCloseTo(130580.6004616969, 2);
    expect(R.facility).toBeCloseTo(1754142.4159321818, 2);
  });

  it('residual, profit, returns', () => {
    expect(R.residualNet).toBeCloseTo(406711.35553408216, 2);
    expect(R.landGross).toBeCloseTo(434367.7277103998, 2);
    expect(R.profit).toBe(855600);
    expect(R.totalCost).toBeCloseTo(3422400, 2);
    expect(R.equity).toBeCloseTo(1543124.396441561, 2);
    expect(R.poc).toBeCloseTo(0.25, 10);
    expect(R.rogdv).toBeCloseTo(0.2, 10);
    expect(R.roe).toBeCloseTo(0.5544595121255359, 8);
    expect(R.holdYears).toBeCloseTo(1.75, 10);
  });

  it('IRRs to the basis point', () => {
    expect(R.cash!.projIrr).toBeCloseTo(0.3059796806842816, 4);
    expect(R.cash!.eqIrr).toBeCloseTo(0.46450411572478023, 4);
    expect(R.cash!.peak).toBeCloseTo(R.facility, 6);
  });

  it('positive land headroom vs ~£400k asking (verdict PROCEED)', () => {
    expect(R.residualNet).toBeGreaterThan(400000);
    expect(R.poc).toBeGreaterThanOrEqual(0.17);
  });

  it('cashflow ledger reconciles: cumulative ends at profit − finance timing effects', () => {
    const rows = R.cash!.rows;
    expect(rows).toHaveLength(21);
    const last = rows[rows.length - 1];
    // Σnet = GDV − saleCosts − construction − land − interest (arrangement not in ledger)
    const expected = R.gdv - R.saleCosts - (R.build + R.fees + R.cont + R.otherTotal) - R.landGross - R.interest;
    expect(last.cum).toBeCloseTo(expected, 2);
  });
});

describe('jvWaterfall — golden fixture', () => {
  const R = computeAppraisal(referenceCase);
  const jv = jvWaterfall(R.equity, R.profit, R.holdYears, referenceCase.jv!);

  it('tiers to the penny', () => {
    expect(jv.gp.equity).toBeCloseTo(154312.4396441561, 2);
    expect(jv.lp.equity).toBeCloseTo(1388811.956797405, 2);
    expect(jv.prefTotal).toBeCloseTo(222476.37339143138, 2);
    expect(jv.residualProfit).toBeCloseTo(633123.6266085686, 2);
    expect(jv.promote).toBeCloseTo(126624.72532171372, 2);
    expect(jv.lp.profit).toBeCloseTo(656077.7472104577, 2);
    expect(jv.gp.profit).toBeCloseTo(199522.25278954237, 2);
  });

  it('MOIC and annualised-MOIC IRR to the basis point', () => {
    expect(jv.lp.moic).toBeCloseTo(1.4724021448687485, 6);
    expect(jv.gp.moic).toBeCloseTo(2.2929758174366235, 6);
    expect(jv.lp.irr!).toBeCloseTo(0.2474269122649, 6);
    expect(jv.gp.irr!).toBeCloseTo(0.6067287206594429, 6);
  });

  it('distributions conserve profit', () => {
    expect(jv.lp.profit + jv.gp.profit).toBeCloseTo(R.profit, 6);
  });

  it('pref-not-cleared: promote is zero, profit split pro-rata', () => {
    const w = jvWaterfall(1_000_000, 50_000, 2, { gpCoinvestPct: 10, prefPct: 8, promotePct: 20 });
    expect(w.promote).toBe(0);
    expect(w.lp.profit).toBeCloseTo(45_000, 6);
    expect(w.gp.profit).toBeCloseTo(5_000, 6);
    expect(w.residualProfit).toBe(0);
  });

  it('zero equity does not divide by zero', () => {
    const w = jvWaterfall(0, 100_000, 2, { gpCoinvestPct: 10, prefPct: 8, promotePct: 20 });
    expect(Number.isFinite(w.gp.profit)).toBe(true);
    expect(w.lp.irr).toBeNull();
  });
});

describe('profit mode', () => {
  it('fixes land and solves profit; residual and profit modes agree at the residual land price', () => {
    const R = computeAppraisal(referenceCase);
    const profitMode: AppraisalInput = {
      ...referenceCase,
      site: { mode: 'profit', landFixed: R.residualNet, acqPct: 6.8 },
    };
    const P = computeAppraisal(profitMode);
    expect(P.residualNet).toBeCloseTo(R.residualNet, 6);
    expect(P.profit).toBeCloseTo(R.profit, 4);
    expect(P.totalCost).toBeCloseTo(R.totalCost, 4);
  });
});

describe('buildSpendProfile', () => {
  it.each(['scurve', 'even', 'linear', 'front', 'back'] as const)('%s sums to 1', (p) => {
    const w = buildSpendProfile(18, p);
    expect(w).toHaveLength(18);
    expect(w.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 12);
  });
  it('front is decreasing, back is increasing', () => {
    const f = buildSpendProfile(6, 'front');
    const b = buildSpendProfile(6, 'back');
    expect(f[0]).toBeGreaterThan(f[5]);
    expect(b[0]).toBeLessThan(b[5]);
  });
  it('scurve peaks mid-programme', () => {
    const s = buildSpendProfile(12, 'scurve');
    const mid = Math.max(...s.slice(4, 8));
    expect(mid).toBeGreaterThan(s[0]);
    expect(mid).toBeGreaterThan(s[11]);
  });
});

describe('irr', () => {
  it('finds the rate for a simple cashflow', () => {
    // -100k now, +110k in one period → 10% (tolerance is |npv| < £1, per the prototype)
    const r = irr([-100_000, 110_000]);
    expect(r!).toBeCloseTo(0.1, 4);
  });
  it('returns null when no sign change (no root)', () => {
    expect(irr([100, 100, 100])).toBeNull();
    expect(irr([-100, -50])).toBeNull();
  });
  it('annualises monthly rate', () => {
    expect(annualise(0.01)!).toBeCloseTo(Math.pow(1.01, 12) - 1, 12);
    expect(annualise(null)).toBeNull();
  });
});

describe('sdltCommercial — UK non-residential slice bands', () => {
  it('£0 up to £150k', () => {
    expect(sdltCommercial(0)).toBe(0);
    expect(sdltCommercial(150_000)).toBe(0);
  });
  it('2% on £150k–£250k slice', () => {
    expect(sdltCommercial(200_000)).toBe(1_000);
    expect(sdltCommercial(250_000)).toBe(2_000);
  });
  it('5% above £250k', () => {
    expect(sdltCommercial(400_000)).toBe(2_000 + 7_500);
    expect(sdltCommercial(1_000_000)).toBe(2_000 + 37_500);
  });
});

describe('cilCharge', () => {
  it('£/sqm × GIA/10.764', () => {
    expect(cilCharge(10_764, 40)).toBeCloseTo(40_000, 6);
    expect(cilCharge(0, 40)).toBe(0);
  });
});

describe('zero units', () => {
  it('computes without NaN/throw', () => {
    const R = computeAppraisal({ ...referenceCase, units: [] });
    expect(R.gdv).toBe(0);
    expect(R.nia).toBe(0);
    expect(Number.isFinite(R.residualNet)).toBe(true);
    expect(R.residualNet).toBeLessThan(0); // costs with no revenue → negative land
  });
});

describe('sensitivityGrid', () => {
  it('5×5 grid, base cell at centre matches base compute', () => {
    const grid = sensitivityGrid(referenceCase, 'roc');
    expect(grid).toHaveLength(5);
    expect(grid[2]).toHaveLength(5);
    const base = grid[2][2];
    expect(base.isBase).toBe(true);
    expect(base.value).toBeCloseTo(0.25, 10);
  });
  it('residual-mode: profit tracks GDV; residual land falls with build cost', () => {
    const profitGrid = sensitivityGrid(referenceCase, 'profit', [-0.1, 0, 0.1]);
    // rows reversed: row 0 = build +10%; col 2 = sales +10%
    expect(profitGrid[1][2].value).toBeGreaterThan(profitGrid[1][1].value);
    // in residual mode build cost hits residual land, not the (fixed target) profit
    const resGrid = sensitivityGrid(referenceCase, 'residual', [-0.1, 0, 0.1]);
    expect(resGrid[0][1].value).toBeLessThan(resGrid[1][1].value);
  });
  it('profit-mode: profit falls with build cost', () => {
    const input: AppraisalInput = { ...referenceCase, site: { mode: 'profit', landFixed: 400_000, acqPct: 6.8 } };
    const grid = sensitivityGrid(input, 'profit', [-0.1, 0, 0.1]);
    expect(grid[0][1].value).toBeLessThan(grid[1][1].value);
  });
});

describe('autoAppraise — indicative model', () => {
  const j = {
    units: [
      { label: 'Trade counter units', count: 6, area: 2600, cap: 225 },
      { label: 'Mezzanine offices', count: 1, area: 3200, cap: 240 },
    ],
    efficiency: 90,
    buildPerSqft: 105,
    profFeePct: 11,
    contingencyPct: 5,
    cilPerSqm: 40,
    s106: 150_000,
    agentPct: 1.5,
    legalPct: 0.5,
    ltcPct: 60,
    ratePct: 7.5,
    periodMonths: 18,
    salesMonths: 3,
    arrangementFeePct: 1.5,
    targetProfitPct: 20,
    acqPct: 6.8,
    asking: 400_000,
  };
  const r = autoAppraise(j);

  it('matches the simplified finance formula exactly', () => {
    const constr = r.build + r.fees + r.cont + r.other;
    expect(r.facility).toBeCloseTo(constr * 0.6, 6);
    expect(r.interest).toBeCloseTo(r.facility * 0.075 * (21 / 12) * 0.55, 6);
    expect(r.arrangement).toBeCloseTo(r.facility * 0.015, 6);
  });
  it('asking-price economics: headroom = residual − asking', () => {
    expect(r.headroom).toBeCloseTo(r.residualNet - 400_000, 6);
    expect(r.askingGross).toBeCloseTo(400_000 * 1.068 + sdltCommercial(400_000), 6);
    expect(r.profitAtAsking! + r.totalCostAtAsking!).toBeCloseTo(r.gdv, 6);
  });
  it('no asking → null asking-fields, sdlt on residual', () => {
    const r0 = autoAppraise({ ...j, asking: 0 });
    expect(r0.headroom).toBeNull();
    expect(r0.sdlt).toBeCloseTo(sdltCommercial(Math.max(r0.residualNet, 0)), 6);
  });
});

describe('weightedComparables — matches the prototype grid', () => {
  it('reproduces the prototype demo derived rate', () => {
    const s = weightedComparables([
      { address: '312 Maplewood Ave', basePsf: 218, adjustments: { size: 2, condition: 4, date: 3, location: 0 } },
      { address: '88 Oakridge Drive', basePsf: 232, adjustments: { size: -3, condition: 0, date: 4, location: -5 } },
      { address: '5 Birch Hollow Court', basePsf: 226, adjustments: { size: 4, condition: 2, date: 6, location: -2 } },
      { address: 'Quayside Industrial', basePsf: 240, adjustments: { size: -6, condition: -4, date: 7, location: 3 } },
    ]);
    expect(s.comps[0].adjustedPsf).toBe(238);
    expect(s.comps[1].adjustedPsf).toBe(223);
    expect(s.comps[2].adjustedPsf).toBe(249);
    expect(s.comps[3].adjustedPsf).toBe(240);
    expect(Math.round(s.supportedPsf)).toBe(237);
    expect(s.range.lo).toBe(223);
    expect(s.range.hi).toBe(249);
  });
});
