import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { documentBlocks } from '../src/routers/appraisal.js';
import { makeTenant, prisma, resetDatabase, type Tenant } from './harness.js';

/**
 * Which documents an extraction can read, and what it says about the rest.
 *
 * The data room's upload control said "PDF, DWG, XLSX · up to 100 MB. Documents
 * feed the AI extraction". `documentBlocks` handled pdf, png, jpg and jpeg, and
 * everything else fell through a bare `continue` — so a valuer who selected their
 * elemental cost plan, which is the example that control's own placeholder uses
 * ("Elemental cost plan v4.xlsx"), got an extraction that had never seen it and
 * nothing saying so. A DWG the same. A partial skip read as a complete success:
 * "Generated by AI from 1 document", with the other silently gone.
 *
 * Two halves. Spreadsheets are READ now, as text, because a cost plan is the most
 * valuable document here after the drawings and `exceljs` was already in the
 * monorepo. And every skip is REPORTED with a reason, because DWG is binary CAD
 * with no text to extract and never will be readable — a model handed the bytes
 * would invent — so the honest thing is to say which document was ignored and
 * what to do about it.
 */

const UPLOADS = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'uploads');
const made: string[] = [];

let T: Tenant;

/** A document row with a real file behind it, or none when `bytes` is null. */
async function doc(name: string, ext: string, bytes: Buffer | null) {
  let url = '';
  if (bytes) {
    const key = `test-${Date.now()}-${Math.random().toString(36).slice(2, 7)}.${ext}`;
    await mkdir(UPLOADS, { recursive: true });
    await writeFile(path.join(UPLOADS, key), bytes);
    made.push(path.join(UPLOADS, key));
    url = `/uploads/files/${key}`;
  }
  return prisma.document.create({
    data: {
      orgId: T.orgId, dealId: T.dealId, name, category: 'Planning', ext,
      sizeBytes: BigInt(bytes?.length ?? 0), url, addedById: T.userId,
    },
  });
}

/** A real workbook, built with the library the server reads it back with. */
async function workbook(rows: Array<Array<string | number>>): Promise<Buffer> {
  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  const sheet = wb.addWorksheet('Cost plan');
  for (const r of rows) sheet.addRow(r);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

const read = (ids: string[]) => documentBlocks(prisma, T.orgId, ids);

beforeAll(async () => {
  resetDatabase();
  T = await makeTenant('ExtractDocs');
}, 120_000);

afterAll(async () => {
  await Promise.all(made.map((f) => rm(f, { force: true })));
});

describe('a spreadsheet is read', () => {
  it('reaches the model as the text of its cells', async () => {
    const d = await doc(
      'Elemental cost plan v4.xlsx',
      'xlsx',
      await workbook([
        ['Package', 'Rate £/ft²', 'Total'],
        ['Substructure', 18, 324000],
        ['Frame & envelope', 72, 1296000],
      ]),
    );
    const { blocks, used, skipped } = await read([d.id]);
    expect(skipped, 'a spreadsheet was skipped').toEqual([]);
    expect(used.map((u) => u.name)).toEqual(['Elemental cost plan v4.xlsx']);
    expect(blocks).toHaveLength(1);
    expect(blocks[0]!.type).toBe('text');
    const text = (blocks[0] as { text: string }).text;
    // the figures a cost plan is for, not just its headings
    expect(text).toContain('Frame & envelope');
    expect(text).toContain('1296000');
    expect(text, 'the block does not say which document it came from').toContain('Elemental cost plan v4.xlsx');
  });

  it('says so when only part of a workbook was read', async () => {
    const rows: Array<Array<string | number>> = [['Package', 'Total']];
    for (let i = 0; i < 500; i++) rows.push([`Line ${i}`, i * 1000]);
    const d = await doc('Huge export.xlsx', 'xlsx', await workbook(rows));
    const { blocks, skipped } = await read([d.id]);
    expect(blocks, 'a long workbook was dropped rather than bounded').toHaveLength(1);
    expect(skipped.map((s) => s.reason).join(' ')).toMatch(/first 400 rows/);
  });

  it('reports a file that is not really a workbook rather than failing the run', async () => {
    const d = await doc('Not really.xlsx', 'xlsx', Buffer.from('this is not a zip archive'));
    const { blocks, skipped } = await read([d.id]);
    expect(blocks).toEqual([]);
    expect(skipped[0]!.reason).toMatch(/could not be opened/);
  });
});

describe('what cannot be read is named, with what to do about it', () => {
  it('names a DWG and says to export it as PDF', async () => {
    const d = await doc('Site plan rev C.dwg', 'dwg', Buffer.from('AC1027 binary'));
    const { blocks, used, skipped } = await read([d.id]);
    expect(blocks).toEqual([]);
    expect(used).toEqual([]);
    expect(skipped).toHaveLength(1);
    expect(skipped[0]!.name).toBe('Site plan rev C.dwg');
    expect(skipped[0]!.reason, 'the reason does not say what to do instead').toMatch(/export the sheet as PDF/i);
  });

  /**
   * The case that read as a complete success. One readable document and one not:
   * the extraction ran, the note said "1 document", and the drawing was gone
   * without a word.
   */
  it('reports the skip even when the other documents read perfectly', async () => {
    const good = await doc('Planning decision.pdf', 'pdf', Buffer.from('%PDF-1.4 decision notice'));
    const bad = await doc('Elevations.dwg', 'dwg', Buffer.from('AC1027'));
    const { used, skipped } = await read([good.id, bad.id]);
    expect(used.map((u) => u.name)).toEqual(['Planning decision.pdf']);
    expect(skipped.map((s) => s.name)).toEqual(['Elevations.dwg']);
  });

  it('names a row the firm is waiting on, which has no file at all', async () => {
    const d = await doc('Awaited cost plan.xlsx', 'xlsx', null);
    const { blocks, skipped } = await read([d.id]);
    expect(blocks).toEqual([]);
    expect(skipped[0]!.reason).toMatch(/no file has been uploaded/i);
  });

  it('names a row whose file has gone from storage', async () => {
    const d = await prisma.document.create({
      data: {
        orgId: T.orgId, dealId: T.dealId, name: 'Vanished.pdf', category: 'Planning', ext: 'pdf',
        sizeBytes: 100n, url: '/uploads/files/not-on-disk-anywhere.pdf', addedById: T.userId,
      },
    });
    const { blocks, skipped } = await read([d.id]);
    expect(blocks).toEqual([]);
    expect(skipped[0]!.reason).toMatch(/could not be read from storage/i);
  });

  /** A format nobody listed still gets a sentence rather than silence. */
  it('names any other format, and says which ones work', async () => {
    const d = await doc('Scope.docx', 'docx', Buffer.from('PK word'));
    const { skipped } = await read([d.id]);
    expect(skipped[0]!.reason).toMatch(/DOCX cannot be read/);
    expect(skipped[0]!.reason).toMatch(/PDF, XLSX, PNG and JPG/);
  });
});

describe('isolation', () => {
  it('reads nothing belonging to another firm', async () => {
    const other = await makeTenant('ExtractDocsOther');
    const theirs = await prisma.document.create({
      data: {
        orgId: other.orgId, dealId: other.dealId, name: 'Their plan.xlsx', category: 'Planning', ext: 'xlsx',
        sizeBytes: 10n, url: '/uploads/files/theirs.xlsx', addedById: other.userId,
      },
    });
    const { blocks, used, skipped } = await read([theirs.id]);
    expect(blocks).toEqual([]);
    expect(used).toEqual([]);
    // not even named: the query never saw it, so there is nothing to report
    expect(skipped).toEqual([]);
  });
});
