import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import Fastify from 'fastify';
import { describe, expect, it } from 'vitest';
import { registerAdmin } from '../src/admin.js';
import { prisma } from '../src/context.js';
import { registerHealth } from '../src/health.js';
import { registerPublicApi } from '../src/public-api.js';
import { registerReports } from '../src/reports.js';
import { registerTiles } from '../src/tiles.js';
import { registerUploads } from '../src/uploads.js';
import { registerWebhooks } from '../src/webhooks.js';

/**
 * The routes that are not procedures.
 *
 * Every mechanical sweep this codebase has walks `appRouter._def.procedures`:
 * isolation, provenance, approved-immutable, lost-update, one-current-read. That
 * is the right mechanism for the 90-odd tRPC procedures and it is blind to the
 * eighteen raw Fastify routes beside them — the uploads, the PDFs, the tile
 * proxy, the public API, the Stripe webhook. A defect that would fail CI inside
 * a procedure ships silently outside one, which is exactly what happened:
 * `POST /uploads/photo` created a site photo and wrote no provenance, while the
 * tRPC `photos.add` two files away wrote one and explained why it mattered.
 *
 * So this asks the raw routes the questions the router sweeps ask, and it walks
 * the REAL server to find them — a Fastify instance with the same registrars
 * `main.ts` uses, collecting routes through `onRoute`. That matters more than it
 * sounds: a grep for `app.post('/...` misses three of these, because the path
 * sits on the line after a generic type parameter, and misses two more entirely.
 * A hand-kept list would have been wrong the day it was written.
 */

const API_SRC = join(import.meta.dirname, '..', 'src');

interface RawRoute {
  method: string;
  url: string;
  source: string;
}

async function realRoutes(): Promise<RawRoute[]> {
  const app = Fastify();
  const found: RawRoute[] = [];
  app.addHook('onRoute', (r) => {
    for (const method of [r.method].flat()) {
      // HEAD is generated by Fastify for every GET; it is the same handler
      if (method !== 'HEAD') found.push({ method, url: r.url, source: r.handler.toString() });
    }
  });
  await registerUploads(app);
  registerReports(app);
  registerTiles(app);
  registerWebhooks(app);
  registerPublicApi(app);
  registerAdmin(app);
  registerHealth(app, prisma);
  await app.ready();
  return found;
}

/** the same two forms and the same named helpers `provenance-sweep` accepts */
const DIRECT = [/recordAudit\(/, /activityEvent\.create\(/];
const HELPERS = [/settlePayment\(/];

/**
 * Mutating routes that write no provenance, each with the reason it does not.
 *
 * The bar is the one `provenance-sweep` sets: not "nothing important happens",
 * but that the event a reader would look for is recorded somewhere else, or
 * there is no reader. Both entries here inherit a judgement already made for the
 * equivalent procedure, rather than making a new one.
 */
const NO_PROVENANCE: Record<string, string> = {
  'POST /admin/reset-demo':
    'wipes and reseeds the demo workspace, activity events included — an event describing it would be deleted by the same call that wrote it. The same reason `org.deleteWorkspace` is exempt in provenance-sweep.',
  'POST /uploads/logo':
    'sets the firm’s logo image. `org.clearLogo` — the same field, in the other direction — is already exempt as "cosmetic: it changes how a document looks, never a figure, a permission or a date", and one direction of a field cannot need a trail the other does not.',
};

const MUTATING = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
const key = (r: RawRoute) => `${r.method} ${r.url}`;

describe('the raw routes', () => {
  it('are found by walking the real server, not by grepping for them', async () => {
    const routes = await realRoutes();
    // a sweep over an empty list passes silently, reporting success for a
    // question it never asked
    expect(routes.length).toBeGreaterThan(10);
    const urls = routes.map(key);
    expect(urls).toContain('POST /uploads/photo');
    expect(urls).toContain('GET /tiles/:z/:x/:y.png');
    // the two a regex over `app.post('/` never saw
    expect(urls).toContain('GET /api/v1/deals');
    expect(urls).toContain('GET /api/v1/deals/:id');
  });

  it('are all registered by this sweep, exactly as main.ts registers them', () => {
    /**
     * The sweep is only as complete as its own import list. `main.ts` is the
     * real one, so a new surface of raw routes fails here the day it is added
     * rather than being quietly unswept.
     */
    const main = readFileSync(join(API_SRC, 'main.ts'), 'utf8');
    const registrars = [...main.matchAll(/\b(register[A-Z]\w*)\(app/g)].map((m) => m[1]);
    const swept = readFileSync(join(import.meta.dirname, 'raw-route-sweep.test.ts'), 'utf8');
    const mine = [...swept.matchAll(/\b(register[A-Z]\w*)\(app/g)].map((m) => m[1]);
    expect(registrars.length).toBeGreaterThan(5);
    // registerSecurity installs hooks rather than routes, so it has none to sweep
    expect([...new Set(registrars)].sort().filter((r) => r !== 'registerSecurity')).toEqual(
      [...new Set(mine)].sort(),
    );
  });

  it('write provenance when they mutate, or say why they do not', async () => {
    const routes = await realRoutes();
    const mutating = routes.filter((r) => MUTATING.has(r.method));
    expect(mutating.length).toBeGreaterThan(3);

    const silent = mutating
      .filter((r) => !DIRECT.some((p) => p.test(r.source)) && !HELPERS.some((p) => p.test(r.source)))
      .map(key)
      .filter((k) => !(k in NO_PROVENANCE));

    expect(
      silent,
      `these raw routes change something and write nothing down. Record it, or add it to NO_PROVENANCE with the reason: ${silent.join(', ')}`,
    ).toEqual([]);
  });

  it('has no exemption for a route that no longer exists', async () => {
    // an exemption outliving its route reads as a considered decision about
    // something that is not there
    const urls = new Set((await realRoutes()).map(key));
    expect(Object.keys(NO_PROVENANCE).filter((k) => !urls.has(k))).toEqual([]);
  });
});
